version: 2
jobs:
  build:
    #working_directory: /go/src/github.com/Preetam/libab
    docker:
      - image: preetamjinka/libab-build:0.0.1
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cd build && cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 ..
      - run: cd build && make -t dep || true
      - run: cd build && make uv uv_a -j
      - run: cd build && make -j
      - run: cd build && make test
      - run: cd build && make install
      - store_artifacts:
          path: /usr/local/lib/libab.so
          destination: libab.so
      - store_artifacts:
          path: /usr/local/include/ab.h
          destination: ab.h
