version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Preetam/libab
    docker:
      - image: preetamjinka/libab-build:0.0.1
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cd build && cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 ..
      - run: cd build && make -t dep || true
      - run: cd build && make uv -j
      - run: cd build && make -j
      - run: cd build && make install
